export const carouselItems = [
  {
    id: 1,
    img: "https://static.nike.com.hk/resources/template/kvFullNewModule3/42395515291894404.jpg",
    color: "",
  },
  {
    id: 2,
    img: "https://static.nike.com.hk/resources/template/kvFullNewModule6/21417696180660895.jpg",
    color: "",
  },
  {
    id: 3,
    img: "",
    color: "",
  },
];

export const categories = [
  {
    id: 1,
    img: "https://img.adidas.com.hk/resources/2023/Jun/summer/pc.jpg",
    title: "Top & T-shirts",
    category: "top",
    color: "",
  },
  {
    id: 2,
    img: "https://img.freepik.com/free-photo/female-outdoor-with-skateboard_23-2148436030.jpg?w=826&t=st=1687420594~exp=1687421194~hmac=c7059da52f2f9ead974dc3293a8c2eb7b2ccf2ada81e0da16abe16e52b79e56f",
    title: "Short & Pants",
    category: "bottom",
    color: "",
  },
  {
    id: 3,
    img: "https://img.freepik.com/free-photo/full-shot-man-posing-stairs_23-2149659151.jpg?w=826&t=st=1687419495~exp=1687420095~hmac=c352b8ff5283652243264df7e34d4df039b8257e001fcfe56089c010652c1fa7",
    category: "jacket",
    title: "Jacket",
    color: "",
  },
];

export const popularProducts = [
  {
    id: 1,
    img: "https://static.nike.com.hk/resources/product/DQ4819-250/DQ4819-250_M1.png",
    category: "top",
    sex: "men",
    title: "A men T-shirt",
    special: true,
    price: 120,
  },
  {
    id: 2,
    img: "https://static.nike.com.hk/resources/product/FJ7227-100/FJ7227-100_M1.png",
    category: "top",
    sex: "men",
    title: "A men T-shirt",
    special: false,
    price: 150,
  },
  {
    id: 3,
    img: "https://static.nike.com.hk/resources/product/FD0057-479/FD0057-479_M1.png",
    category: "top",
    sex: "men",
    title: "A men T-shirt",
    special: false,
    price: 220,
  },
  {
    id: 4,
    img: "https://static.nike.com.hk/resources/product/DV7961-100/DV7961-100_M1.png",
    category: "top",
    sex: "women",
    title: "A women T-shirt",
    special: false,
    price: 120,
  },
  {
    id: 5,
    img: "https://static.nike.com.hk/resources/product/DV7863-010/DV7863-010_M1.png",
    category: "bottom",
    sex: "women",
    title: "A women pant",
    special: true,
    price: 320,
  },
  {
    id: 6,
    img: "https://static.nike.com.hk/resources/product/FJ7711-133/FJ7711-133_M1.png",
    category: "jacket",
    sex: "women",
    title: "A women jacket",
    special: false,
    price: 250,
  },
  {
    id: 7,
    img: "https://static.nike.com.hk/resources/product/DX0218-491/DX0218-491_M1.png",
    category: "jacket",
    sex: "men",
    title: "A men jacket",
    special: false,
    price: 399,
  },
  {
    id: 8,
    img: "https://static.nike.com.hk/resources/product/DR0100-010/DR0100-010_M1.png",
    category: "jacket",
    sex: "men women",
    title: "An unisexal jacket",
    special: true,
    price: 1200,
  },
  // {
  //   id: 9,
  //   img: "https://static.nike.com.hk/resources/product/DA0324-836/DA0324-836_M1.png",
  //   category: "top",
  //   sex: "women",
  //   price: 3200,
  //   title: "A women top",
  //   special: false,
  // },
  // {
  //   id: 10,
  //   img: "https://static.nike.com.hk/resources/product/DX0622-030/DX0622-030_M1.png",
  //   category: "bottom",
  //   sex: "men",
  //   title: "A men pant",
  //   special: true,
  //   price: 200,
  // },
];

export const allProducts = [
  {
    id: 1,
    img: "https://static.nike.com.hk/resources/product/DQ4819-250/DQ4819-250_M1.png",
    category: "top",
    sex: ["men"],
    title: "Men's Short-Sleeve Fitness Top",
    special: true,
    price: 120,
    des: "Your busy day means you need to be ready to exercise at any time. We made the Axis Performance System (A.P.S.) Top to answer the challenge with a smooth, stretchy and breathable feel that can be worn for your workout and beyond. Wear it on its own or as a layering piece to help you reach peak performance.",
  },
  {
    id: 2,
    img: "https://static.nike.com.hk/resources/product/FJ7227-100/FJ7227-100_M1.png",
    category: "top",
    sex: ["men"],
    title: "A men T-shirt",
    special: false,
    price: 150,
    des: "We made our pinnacle Run Division Top with advanced sweat-wicking technology, so you stay dry and cling-free when the heat hits your route. Your run is your getaway, so we made this one smooth, soft and light for comfort with every step. Plus, a bold graphic adds some teeth to your running journey.",
  },
  {
    id: 3,
    img: "https://static.nike.com.hk/resources/product/FD0057-479/FD0057-479_M1.png",
    category: "top",
    sex: ["men"],
    title: "A men T-shirt",
    special: false,
    price: 220,
    des: "The Nike Pro Dri-FIT Top helps keep you cool, dry and moving feely through your workout. This product contains recycled polyester fibers.",
  },
  {
    id: 4,
    img: "https://static.nike.com.hk/resources/product/DV7961-100/DV7961-100_M1.png",
    category: "top",
    sex: ["women"],
    title: "A women T-shirt",
    special: false,
    price: 120,
    des: "Throw on this body-skimming tank and enjoy the feel of stretchy, ribbed fabric. With a cropped fit that hits near the waist, this wardrobe staple can be worn around the clock and all through the calendar.",
  },
  {
    id: 5,
    img: "https://static.nike.com.hk/resources/product/DV7863-010/DV7863-010_M1.png",
    category: "bottom",
    sex: ["women"],
    title: "A women pant",
    special: true,
    price: 320,
  },
  {
    id: 6,
    img: "https://static.nike.com.hk/resources/product/FJ7711-133/FJ7711-133_M1.png",
    category: "jacket",
    sex: ["women"],
    title: "A women jacket",
    special: false,
    price: 250,
  },
  {
    id: 7,
    img: "https://static.nike.com.hk/resources/product/DX0218-491/DX0218-491_M1.png",
    category: "jacket",
    sex: ["men"],
    title: "A men jacket",
    special: false,
    price: 399,
  },
  {
    id: 8,
    img: "https://static.nike.com.hk/resources/product/DR0100-010/DR0100-010_M1.png",
    category: "jacket",
    sex: ["men", "women"],
    title: "An unisexal jacket",
    special: true,
    price: 1200,
  },
  {
    id: 9,
    img: "https://static.nike.com.hk/resources/product/DA0324-836/DA0324-836_M1.png",
    category: "top",
    sex: ["women"],
    price: 3200,
    title: "A women top",
    special: false,
  },
  {
    id: 10,
    img: "https://static.nike.com.hk/resources/product/DX0622-030/DX0622-030_M1.png",
    category: "bottom",
    sex: ["men"],
    title: "A men pant",
    special: true,
    price: 200,
  },

  {
    id: 11,
    img: "https://static.nike.com.hk/resources/product/FB0946-808/FB0946-808_M1.png",
    category: "jacket",
    sex: ["kids"],
    title: "A kid jacket",
    special: false,
    price: 500,
  },
  {
    id: 12,
    img: "https://static.nike.com.hk/resources/product/HA2543-101/HA2543-101_M1.png",
    category: "top",
    sex: ["kids"],
    title: "A kid t-shirt",
    special: false,
    price: 300,
  },
  {
    id: 13,
    img: "https://static.nike.com.hk/resources/product/DR8097-687/DR8097-687_M1.png",
    category: "bottom",
    sex: ["kids"],
    title: "A kid short",
    special: true,
    price: 350,
  },
  {
    id: 14,
    img: "https://static.nike.com.hk/resources/product/FD5371-100/FD5371-100_M1.png",
    category: "top",
    sex: ["kids"],
    title: "A kid t-shirt",
    special: false,
    price: 370,
  },

  {
    id: 15,
    img: "https://static.nike.com.hk/resources/product/FJ9624-030/FJ9624-030_M1.png",
    category: "jacket",
    sex: ["kids"],
    title: "A kid jacket",
    special: false,
    price: 570,
  },
];
